---
# - name: Install Requirements
#   apt:
#     name:
#       - resolvconf
#     update_cache: yes

# - name: Add DNS Addresses
#   blockinfile:
#     path: /etc/resolvconf/resolv.conf.d/head
#     block: |
#       nameserver 1.1.1.1
#       nameserver 8.8.8.8
#       nameserver 3.3.3.3
#       nameserver 4.2.2.4
#   notify: restart resolvconf

# - name: Install dependencies
#   import_tasks: kube-dependencies.yml

- name: Preinstallation
  import_tasks: preinstallation.yml

- name: Copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts


